#spring链接数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taxi?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#集成mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: example.bean
#打印日志
logging:
  level:
    example:
      dao: TRACE
